#!/usr/bin/env bash
set -e
set -u
# Refresh source data, produce a data report and load the import mapping
./museum/importObjects -rpm
# Run the import
./museum/importObjects
./museum/importSubjects -rm
./museum/importSubjects
caUtils rebuild-search-index
