#!/usr/bin/env bash
set -e
set -u
# Refresh source object data, produce a data report and load the object import mapping
./museum/importObjects -rpm
# Run the object import
./museum/importObjects

# Refresh source subject data, refresh the data report and load the object import mapping
./museum/importSubjects -rpm
# Run the subject import
./museum/importSubjects

# Rebuild the search index
caUtils rebuild-search-index
