#!/usr/bin/env bash

# halt on any errors or undefined variables
set -e
set -u

# load environment settings
pushd `dirname "$0"`>/dev/null
source ../env
source ../bin/importData
function refreshData() {
    sqltransform LocationHistoryCleaned.sql
    sqltransform LocationHistoryExportView.sql
}

# setup local variables
mapping=rwahsLocationHistoryMapping
mapping_id="1qIQ9YRaICpi0euGT8HFaLuMC17l8DoCqPTCroIUyYIY"
# https://docs.google.com/spreadsheets/d/1qIQ9YRaICpi0euGT8HFaLuMC17l8DoCqPTCroIUyYIY/edit#gid=0

mapping_machine_name=locationHistory
sourceTable=LocationHistoryExport

importData "$@"
popd > /dev/null
