#!/usr/bin/env bash

# halt on any errors or undefined variables
set -e
set -u

# load environment settings
pushd `dirname "$0"`>/dev/null
source ../env
source ../bin/importData
function refreshData() {
    sqltransform LocationHomesCleaned.sql
    sqltransform ObjectsExportView.sql
}

# setup local variables
mapping=rwahsMuseumMapping
mapping_id="11ynTouvmgYI-RoesX3rbvi4xUAhiwTCsOcoUwGLqVHc"
# https://docs.google.com/spreadsheets/d/11ynTouvmgYI-RoesX3rbvi4xUAhiwTCsOcoUwGLqVHc/edit?usp=sharing

mapping_machine_name=museum
sourceTable=ObjectsExport

importData "$@"
popd > /dev/null
