DROP TABLE IF EXISTS LocationHomesCleaned;
CREATE TABLE LocationHomesCleaned (
    # match the source data data type and length
    UsualLocation VARCHAR(200) PRIMARY KEY,
    Room          VARCHAR(255),
    Shelf         VARCHAR(255),
    Box           VARCHAR(255)
);
# Loading transformed values into the database so a single source value can tranform into a hierarchy
INSERT INTO LocationHomesCleaned (UsualLocation, Room, Shelf, Box) VALUES
    ("l", NULL, NULL, NULL),
    ("111 St. George's Terrace, Perth", NULL, NULL, NULL),
    ("139 St. George's Tce., Perth", NULL, NULL, NULL),
    ("140 St. George's Tce., Perth", NULL, NULL, NULL),
    ("240 St. George's Tce., Perth", NULL, NULL, NULL),
    ("381 Murray St., Perth", "382 Murray St., Perth", NULL, NULL),
    ("Artworks Storeroom Floor", "Artworks Storeroom", "Floor", NULL),
    ("Artworks Storeroom North Wall Floor", "Artworks Storeroom", "North Wall floor", NULL),
    ("Artworks Storeroom Shelf A", NULL, NULL, NULL),
    ("Artworks Storeroom Shelf B", "Artworks Storeroom", "B", NULL),
    ("Artworks Storeroom Shelf C", "Artworks Storeroom", "C", NULL),
    ("Artworks Storeroom Shelf L", "Artworks Storeroom", "L", NULL),
    ("Barrack st., Perth", NULL, NULL, NULL),
    ("Cnr. Barrack & Hay Sts., Perth", NULL, NULL, NULL),
    ("Cnr. St. George's Tce. & Mount St., Perth", NULL, NULL, NULL),
    ("Container", "Container", NULL, NULL),
    ("Costume Room", "Costume Room", NULL, NULL),
    ("Costume Room Box 035", "Costume Room", NULL, "Box 035"),
    ("Costume Room Box 100", "Costume Room", NULL, "Box 100"),
    ("Costume Room Box 101", "Costume Room", NULL, "Box 101"),
    ("Costume Room Box 102", "Costume Room", NULL, "Box 102"),
    ("Costume Room Box 103", "Costume Room", NULL, "Box 103"),
    ("Costume Room Box 104", "Costume Room", NULL, "Box 104"),
    ("Costume Room Box 105", "Costume Room", NULL, "Box 105"),
    ("Costume Room Box 106", "Costume Room", NULL, "Box 106"),
    ("Costume Room Box 107", "Costume Room", NULL, "Box 107"),
    ("Costume Room Box 108", "Costume Room", NULL, "Box 108"),
    ("Costume Room Box 109", "Costume Room", NULL, "Box 109"),
    ("Costume Room Box 011", "Costume Room", NULL, "Box 011"),
    ("Costume Room Box 110", "Costume Room", NULL, "Box 110"),
    ("Costume Room Box 111", "Costume Room", NULL, "Box 111"),
    ("Costume Room Box 112", "Costume Room", NULL, "Box 112"),
    ("Costume Room Box 113", "Costume Room", NULL, "Box 113"),
    ("Costume Room Box 114", "Costume Room", NULL, "Box 114"),
    ("Costume Room Box 115", "Costume Room", NULL, "Box 115"),
    ("Costume Room Box 116", "Costume Room", NULL, "Box 116"),
    ("Costume Room Box 117", "Costume Room", NULL, "Box 117"),
    ("Costume Room Box 118", "Costume Room", NULL, "Box 118"),
    ("Costume Room Box 119", "Costume Room", NULL, "Box 119"),
    ("Costume Room Box 012", "Costume Room", NULL, "Box 012"),
    ("Costume Room Box 121", "Costume Room", NULL, "Box 121"),
    ("Costume Room Box 122", "Costume Room", NULL, "Box 122"),
    ("Costume Room Box 123", "Costume Room", NULL, "Box 123"),
    ("Costume Room Box 124", "Costume Room", NULL, "Box 124"),
    ("Costume Room Box 125", "Costume Room", NULL, "Box 125"),
    ("Costume Room Box 126", "Costume Room", NULL, "Box 126"),
    ("Costume Room Box 127", "Costume Room", NULL, "Box 127"),
    ("Costume Room Box 128", "Costume Room", NULL, "Box 128"),
    ("Costume Room Box 129", "Costume Room", NULL, "Box 129"),
    ("Costume Room Box 013", "Costume Room", NULL, "Box 013"),
    ("Costume Room Box 130", "Costume Room", NULL, "Box 130"),
    ("Costume Room Box 131", "Costume Room", NULL, "Box 131"),
    ("Costume Room Box 132", "Costume Room", NULL, "Box 132"),
    ("Costume Room Box 133", "Costume Room", NULL, "Box 133"),
    ("Costume Room Box 134", "Costume Room", NULL, "Box 134"),
    ("Costume Room Box 135", "Costume Room", NULL, "Box 135"),
    ("Costume Room Box 136", "Costume Room", NULL, "Box 136"),
    ("Costume Room Box 137", "Costume Room", NULL, "Box 137"),
    ("Costume Room Box 138", "Costume Room", NULL, "Box 138"),
    ("Costume Room Box 139", "Costume Room", NULL, "Box 139"),
    ("Costume Room Box 140", "Costume Room", NULL, "Box 140"),
    ("Costume Room Box 142", "Costume Room", NULL, "Box 142"),
    ("Costume Room Box 143 - 144", "Costume Room", NULL, "Box 143 - 144"),
    ("Costume Room Box 145", "Costume Room", NULL, "Box 145"),
    ("Costume Room Box 146", "Costume Room", NULL, "Box 146"),
    ("Costume Room Box 147", "Costume Room", NULL, "Box 147"),
    ("Costume Room Box 148", "Costume Room", NULL, "Box 148"),
    ("Costume Room Box 149", "Costume Room", NULL, "Box 149"),
    ("Costume Room Box 150", "Costume Room", NULL, "Box 150"),
    ("Costume Room Box 151", "Costume Room", NULL, "Box 151"),
    ("Costume Room Box 152", "Costume Room", NULL, "Box 152"),
    ("Costume Room Box 153", "Costume Room", NULL, "Box 153"),
    ("Costume Room Box 154", "Costume Room", NULL, "Box 154"),
    ("Costume Room Box 155", "Costume Room", NULL, "Box 155"),
    ("Costume Room Box 156", "Costume Room", NULL, "Box 156"),
    ("Costume Room Box 157", "Costume Room", NULL, "Box 157"),
    ("Costume Room Box 158", "Costume Room", NULL, "Box 158"),
    ("Costume Room Box 159", "Costume Room", NULL, "Box 159"),
    ("Costume Room Box 016", "Costume Room", NULL, "Box 016"),
    ("Costume Room Box 160", "Costume Room", NULL, "Box 160"),
    ("Costume Room Box 161", "Costume Room", NULL, "Box 161"),
    ("Costume Room Box 162", "Costume Room", NULL, "Box 162"),
    ("Costume Room Box 163", "Costume Room", NULL, "Box 163"),
    ("Costume Room Box 164", "Costume Room", NULL, "Box 164"),
    ("Costume Room Box 165", "Costume Room", NULL, "Box 165"),
    ("Costume Room Box 166", "Costume Room", NULL, "Box 166"),
    ("Costume Room Box 167", "Costume Room", NULL, "Box 167"),
    ("Costume Room Box 168", "Costume Room", NULL, "Box 168"),
    ("Costume Room Box 169", "Costume Room", NULL, "Box 169"),
    ("Costume Room Box 017", "Costume Room", NULL, "Box 017"),
    ("Costume Room Box 170", "Costume Room", NULL, "Box 170"),
    ("Costume Room Box 171", "Costume Room", NULL, "Box 171"),
    ("Costume Room Box 172", "Costume Room", NULL, "Box 172"),
    ("Costume Room Box 174", "Costume Room", NULL, "Box 174"),
    ("Costume Room Box 175", "Costume Room", NULL, "Box 175"),
    ("Costume Room Box 176", "Costume Room", NULL, "Box 176"),
    ("Costume Room Box 177", "Costume Room", NULL, "Box 177"),
    ("Costume Room Box 178", "Costume Room", NULL, "Box 178"),
    ("Costume Room Box 179", "Costume Room", NULL, "Box 179"),
    ("Costume Room Box 180", "Costume Room", NULL, "Box 180"),
    ("Costume Room Box 181", "Costume Room", NULL, "Box 181"),
    ("Costume Room Box 182", "Costume Room", NULL, "Box 182"),
    ("Costume Room Box 183", "Costume Room", NULL, "Box 183"),
    ("Costume Room Box 184", "Costume Room", NULL, "Box 184"),
    ("Costume Room Box 185", "Costume Room", NULL, "Box 185"),
    ("Costume Room Box 186", "Costume Room", NULL, "Box 186"),
    ("Costume Room Box 187", "Costume Room", NULL, "Box 187"),
    ("Costume Room Box 189", "Costume Room", NULL, "Box 189"),
    ("Costume Room Box 019", "Costume Room", NULL, "Box 019"),
    ("Costume Room Box 190", "Costume Room", NULL, "Box 190"),
    ("Costume Room Box 191", "Costume Room", NULL, "Box 191"),
    ("Costume Room Box 192", "Costume Room", NULL, "Box 192"),
    ("Costume Room box 193", "Costume Room", NULL, "box 193"),
    ("Costume Room Box 195", "Costume Room", NULL, "Box 195"),
    ("Costume Room Box 197", "Costume Room", NULL, "Box 197"),
    ("Costume Room Box 198", "Costume Room", NULL, "Box 198"),
    ("Costume Room Box 199", "Costume Room", NULL, "Box 199"),
    ("Costume Room Box 200", "Costume Room", NULL, "Box 200"),
    ("Costume Room Box 201", "Costume Room", NULL, "Box 201"),
    ("Costume Room Box 202", "Costume Room", NULL, "Box 202"),
    ("Costume Room Box 203", "Costume Room", NULL, "Box 203"),
    ("Costume Room Box 204", "Costume Room", NULL, "Box 204"),
    ("Costume Room Box 205", "Costume Room", NULL, "Box 205"),
    ("Costume Room Box 206", "Costume Room", NULL, "Box 206"),
    ("Costume Room Box 207", "Costume Room", NULL, "Box 207"),
    ("Costume Room Box 208", "Costume Room", NULL, "Box 208"),
    ("Costume Room Box 209", "Costume Room", NULL, "Box 209"),
    ("Costume Room Box 210", "Costume Room", NULL, "Box 210"),
    ("Costume Room Box 211", "Costume Room", NULL, "Box 211"),
    ("Costume Room Box 212", "Costume Room", NULL, "Box 212"),
    ("Costume Room Box 213", "Costume Room", NULL, "Box 213"),
    ("Costume Room Box 214", "Costume Room", NULL, "Box 214"),
    ("Costume Room Box 215", "Costume Room", NULL, "Box 215"),
    ("Costume Room Box 216", "Costume Room", NULL, "Box 216"),
    ("Costume Room Box 217", "Costume Room", NULL, "Box 217"),
    ("Costume Room Box 218", "Costume Room", NULL, "Box 218"),
    ("Costume Room Box 219", "Costume Room", NULL, "Box 219"),
    ("Costume Room Box 022", "Costume Room", NULL, "Box 022"),
    ("Costume Room Box 220", "Costume Room", NULL, "Box 220"),
    ("Costume Room Box 023", "Costume Room", NULL, "Box 023"),
    ("Costume Room Box 230", "Costume Room", NULL, "Box 230"),
    ("Costume Room Box 231", "Costume Room", NULL, "Box 231"),
    ("Costume Room Box 232", "Costume Room", NULL, "Box 232"),
    ("Costume Room Box 233", "Costume Room", NULL, "Box 233"),
    ("Costume Room Box 234", "Costume Room", NULL, "Box 234"),
    ("Costume Room Box 237", "Costume Room", NULL, "Box 237"),
    ("Costume Room Box 024", "Costume Room", NULL, "Box 024"),
    ("Costume Room Box 025", "Costume Room", NULL, "Box 025"),
    ("Costume Room Box 026", "Costume Room", NULL, "Box 026"),
    ("Costume Room Box 027", "Costume Room", NULL, "Box 027"),
    ("Costume Room Box 028", "Costume Room", NULL, "Box 028"),
    ("Costume Room Box 029", "Costume Room", NULL, "Box 029"),
    ("Costume Room Box 031", "Costume Room", NULL, "Box 031"),
    ("Costume Room Box 032", "Costume Room", NULL, "Box 032"),
    ("Costume Room Box 033", "Costume Room", NULL, "Box 033"),
    ("Costume Room Box 034", "Costume Room", NULL, "Box 034"),
    ("Costume Room Box 036", "Costume Room", NULL, "Box 036"),
    ("Costume Room Box 037", "Costume Room", NULL, "Box 037"),
    ("Costume Room Box 038", "Costume Room", NULL, "Box 038"),
    ("Costume Room Box 039", "Costume Room", NULL, "Box 039"),
    ("Costume Room Box 004", "Costume Room", NULL, "Box 004"),
    ("Costume Room Box 040", "Costume Room", NULL, "Box 040"),
    ("Costume Room Box 041", "Costume Room", NULL, "Box 041"),
    ("Costume Room Box 042", "Costume Room", NULL, "Box 042"),
    ("Costume Room Box 043", "Costume Room", NULL, "Box 043"),
    ("Costume Room Box 044", "Costume Room", NULL, "Box 044"),
    ("Costume Room Box 045", "Costume Room", NULL, "Box 045"),
    ("Costume Room Box 046", "Costume Room", NULL, "Box 046"),
    ("Costume Room Box 047", "Costume Room", NULL, "Box 047"),
    ("Costume Room Box 048", "Costume Room", NULL, "Box 048"),
    ("Costume Room Box 049", "Costume Room", NULL, "Box 049"),
    ("Costume Room Box 005", "Costume Room", NULL, "Box 005"),
    ("Costume Room Box 050", "Costume Room", NULL, "Box 050"),
    ("Costume Room Box 051", "Costume Room", NULL, "Box 051"),
    ("Costume Room Box 052", "Costume Room", NULL, "Box 052"),
    ("Costume Room Box 053", "Costume Room", NULL, "Box 053"),
    ("Costume Room Box 054", "Costume Room", NULL, "Box 054"),
    ("Costume Room Box 055", "Costume Room", NULL, "Box 055"),
    ("Costume Room Box 056", "Costume Room", NULL, "Box 056"),
    ("Costume Room Box 057", "Costume Room", NULL, "Box 057"),
    ("Costume Room Box 058", "Costume Room", NULL, "Box 058"),
    ("Costume Room Box 059", "Costume Room", NULL, "Box 059"),
    ("Costume Room Box 060", "Costume Room", NULL, "Box 060"),
    ("Costume Room Box 061", "Costume Room", NULL, "Box 061"),
    ("Costume Room Box 062", "Costume Room", NULL, "Box 062"),
    ("Costume Room Box 063", "Costume Room", NULL, "Box 063"),
    ("Costume Room Box 064", "Costume Room", NULL, "Box 064"),
    ("Costume Room Box 065", "Costume Room", NULL, "Box 065"),
    ("Costume Room Box 066", "Costume Room", NULL, "Box 066"),
    ("Costume Room Box 067", "Costume Room", NULL, "Box 067"),
    ("Costume Room Box 068", "Costume Room", NULL, "Box 068"),
    ("Costume Room Box 069", "Costume Room", NULL, "Box 069"),
    ("Costume Room Box 007", "Costume Room", NULL, "Box 007"),
    ("Costume Room Box 070", "Costume Room", NULL, "Box 070"),
    ("Costume Room Box 071", "Costume Room", NULL, "Box 071"),
    ("Costume Room Box 076", "Costume Room", NULL, "Box 076"),
    ("Costume Room Box 078", "Costume Room", NULL, "Box 078"),
    ("Costume Room Box 079", "Costume Room", NULL, "Box 079"),
    ("Costume Room Box 008", "Costume Room", NULL, "Box 008"),
    ("Costume Room Box 080", "Costume Room", NULL, "Box 080"),
    ("Costume Room Box 081", "Costume Room", NULL, "Box 081"),
    ("Costume Room Box 082", "Costume Room", NULL, "Box 082"),
    ("Costume Room Box 083", "Costume Room", NULL, "Box 083"),
    ("Costume Room Box 084", "Costume Room", NULL, "Box 084"),
    ("Costume Room Box 085-086", "Costume Room", NULL, "Box 085-086"),
    ("Costume Room Box 086", "Costume Room", NULL, "Box 086"),
    ("Costume Room Box 087", "Costume Room", NULL, "Box 087"),
    ("Costume Room Box 088", "Costume Room", NULL, "Box 088"),
    ("Costume Room Box 089", "Costume Room", NULL, "Box 089"),
    ("Costume Room Box 009", "Costume Room", NULL, "Box 009"),
    ("Costume Room Box 091", "Costume Room", NULL, "Box 091"),
    ("Costume Room Box 092", "Costume Room", NULL, "Box 092"),
    ("Costume Room Box 093", "Costume Room", NULL, "Box 093"),
    ("Costume Room Box 094", "Costume Room", NULL, "Box 094"),
    ("Costume Room Box 095", "Costume Room", NULL, "Box 095"),
    ("Costume Room Box 097", "Costume Room", NULL, "Box 097"),
    ("Costume Room Box 098", "Costume Room", NULL, "Box 098"),
    ("Costume Room Box 099", "Costume Room", NULL, "Box 099"),
    ("Costume Room Hat Box Shelf", "Costume Room", NULL, "Hat Box Shelf"),
    ("Costume Room Top Shelf Box A", "Costume Room", NULL, "Top Shelf Box A"),
    ("Costume Room Top Shelf Box B", "Costume Room", NULL, "Top Shelf Box B"),
    ("Costume Room Top Shelf Box D", "Costume Room", NULL, "Top Shelf Box D"),
    ("Costume Room Top Shelf Box E", "Costume Room", NULL, "Top Shelf Box E"),
    ("Costume Room Top Shelf Box F", "Costume Room", NULL, "Top Shelf Box F"),
    ("Costume Room Top Shelf Box G", "Costume Room", NULL, "Top Shelf Box G"),
    ("Costume Room Top Shelf Box H", "Costume Room", NULL, "Top Shelf Box H"),
    ("Costume Room Top Shelf Box i", "Costume Room", NULL, "Top Shelf Box i"),
    ("Costume Room Top Shelf Box J", "Costume Room", NULL, "Top Shelf Box J"),
    ("Costume Room Top Shelf Box K", "Costume Room", NULL, "Top Shelf Box K"),
    ("Costume Room Top Shelf Box L", "Costume Room", NULL, "Top Shelf Box L"),
    ("Costume Room Top Shelf Box M", "Costume Room", NULL, "Top Shelf Box M"),
    ("Costume Room Top Shelf Box P", "Costume Room", NULL, "Top Shelf Box P"),
    ("Costume Room Top Shelf Box Q", "Costume Room", NULL, "Top Shelf Box Q"),
    ("Costume Room Top Shelf Box R", "Costume Room", NULL, "Top Shelf Box R"),
    ("Costume Room Top Shelf Box S", "Costume Room", NULL, "Top Shelf Box S"),
    ("Drawing Room, Book Cupboard", NULL, NULL, NULL),
    ("East Perth Cemetery, Perth", "East Perth Cemetery, Perth", NULL, NULL),
    ("East Wall Cabinet, Top Room", "Top Room", "East Wall Cabinet", NULL),
    ("Entry to King's Park, Perth", NULL, NULL, NULL),
    ("Foyer", "Foyer", NULL, NULL),
    ("Foyer Bookcase", "Foyer", "Bookcase", NULL),
    ("Foyer Showcase", "Foyer", "Showcase", NULL),
    ("General Store Room", "General Store Room", NULL, NULL),
    ("Gun Cabinet in the Passage", "Passage", "Gun Cabinet", NULL),
    ("Hyde Park, North Perth", "Hyde Park, North Perth", NULL, NULL),
    ("Imp 3", NULL, "Imp 4", NULL),
    ("L1", NULL, NULL, NULL),
    ("L2", NULL, NULL, NULL),
    ("L6", NULL, NULL, NULL),
    ("Laboratory", "Laboratory", NULL, NULL),
    ("Library", "Library", NULL, NULL),
    ("Library Annex,  Map Cabinet, Drawer 2", "Library", "Annex, Map Cabinet, Drawer 2", NULL),
    ("Library Annexe", NULL, NULL, NULL),
    ("Linen Cupboard Box 8", NULL, NULL, NULL),
    ("Locked Storeoom  C3", NULL, NULL, NULL),
    ("Locked Storeroom", "Locked Storeoom", "B3", NULL),
    ("Locked Storeroom A10", NULL, NULL, NULL),
    ("Locked Storeroom B7", NULL, NULL, NULL),
    ("Locked Storeroom B9", NULL, NULL, NULL),
    ("Locked Storeroom C1", NULL, NULL, NULL),
    ("Locked Storeroom w/framed photographs", "Locked Storeoom", "with framed photographs", NULL),
    ("Meeting Room", "Meeting Room", NULL, NULL),
    ("Murray St. Mall, Perth", NULL, NULL, NULL),
    ("Museum Room (Tranby Room)", "Tranby Room", NULL, NULL),
    ("Negative & Proof File", NULL, "Negative & Proof File", NULL),
    ("Object Data Sheet File 'D'", NULL, NULL, NULL),
    ("OUTSIDE MUSEUM, CLARK ST WALL", "OUTSIDE MUSEUM, CLARK ST WALL", NULL, NULL),
    ("OUTSIDE STIRLING HOUSE", "OUTSIDE STIRLING HOUSE", NULL, NULL),
    ("Parmelia Hotel, Perth", "Parmelia Hotel, Perth", NULL, NULL),
    ("Photographs Room", "Photographs Room", NULL, NULL),
    ("Photographs Room, B", "Photographs Room", "B", NULL),
    ("Photographs Room, Cabinet 1,", "Photographs Room", "Cabinet 1", NULL),
    ("Photographs Room, Cabinet 2,", "Photographs Room", "Cabinet 2", NULL),
    ("Photographs Room, CV1", "Photographs Room", "CV1", NULL),
    ("Photographs Room, CV1,", "Photographs Room", "CV1", NULL),
    ("Photographs Room, CV2,", "Photographs Room", "CV2", NULL),
    ("Photographs Room, CV3", "Photographs Room", "CV3", NULL),
    ("Photographs Room, CV3,", "Photographs Room", "CV3", NULL),
    ("Photographs Room, Imp 1,", "Photographs Room", "Imp 1", NULL),
    ("Photographs Room, PC1", "Photographs Room", "PC1", NULL),
    ("Photographs Room, PC2", "Photographs Room", "PC2", NULL),
    ("Photographs Room, PC3", "Photographs Room", "PC3", NULL),
    ("Photographs Room, PC4,", "Photographs Room", "PC4", NULL),
    ("Photographs Room, PC5,", "Photographs Room", "PC5", NULL),
    ("Records Store Room", NULL, NULL, NULL),
    ("Showcase, Upright Top Room", "Top Room", "Upright Showcase", NULL),
    ("St. George's Terrace, Perth", NULL, NULL, NULL),
    ("Storeroom", "Storeroom", NULL, NULL),
    ("Storeroom E01", "Storeroom", "E01", NULL),
    ("Storeroom E02", "Storeroom", "E02", NULL),
    ("Storeroom E03", "Storeroom", "E03", NULL),
    ("Storeroom E04", "Storeroom", "E04", NULL),
    ("Storeroom E05", "Storeroom", "E05", NULL),
    ("Storeroom E06", "Storeroom", "E06", NULL),
    ("Storeroom E07", "Storeroom", "E07", NULL),
    ("Storeroom NA01 No1", "Storeroom", "NA01", "No1"),
    ("Storeroom NA01 No2", "Storeroom", "NA01", "No2"),
    ("Storeroom NA01 No3", "Storeroom", "NA01", "No3"),
    ("Storeroom NA02 No1", "Storeroom", "NA02", "No1"),
    ("Storeroom NA02 No2", "Storeroom", "NA02", "No2"),
    ("Storeroom NA03 No1", "Storeroom", "NA03", "No1"),
    ("Storeroom NA03 No2", "Storeroom", "NA03", "No2"),
    ("Storeroom NA03 No3", "Storeroom", "NA03", "No3"),
    ("Storeroom NA04 No1", "Storeroom", "NA04", "No1"),
    ("Storeroom NA04 No2", "Storeroom", "NA04", "No2"),
    ("Storeroom NA05 No1", "Storeroom", "NA05", "No1"),
    ("Storeroom NA05 No2", "Storeroom", "NA05", "No2"),
    ("Storeroom NA06 No1", "Storeroom", "NA06", "No1"),
    ("Storeroom NA06 No2", "Storeroom", "NA06", "No2"),
    ("Storeroom NA06 No3", "Storeroom", "NA06", "No3"),
    ("Storeroom NA07 No1", "Storeroom", "NA07", "No1"),
    ("Storeroom NA07 No2", "Storeroom", "NA07", "No2"),
    ("Storeroom NA07 No3", "Storeroom", "NA07", "No3"),
    ("Storeroom NA08 No1", "Storeroom", "NA08", "No1"),
    ("Storeroom NA08 No2", "Storeroom", "NA08", "No2"),
    ("Storeroom NA08a No2", "Storeroom", "NA08a", "No2"),
    ("Storeroom NA09 No1", "Storeroom", "NA09", "No1"),
    ("Storeroom NA09 No2", "Storeroom", "NA09", "No2"),
    ("Storeroom NA09 No3", "Storeroom", "NA09", "No3"),
    ("Storeroom NA10 No1", "Storeroom", "NA10", "No1"),
    ("Storeroom NA10 No2", "Storeroom", "NA10", "No2"),
    ("Storeroom NA10 No3", "Storeroom", "NA10", "No3"),
    ("Storeroom NA7 (3)", "Storeroom", "NA7", "3"),
    ("Storeroom NB01 No1", "Storeroom", "NB01", "No1"),
    ("Storeroom NB01 No2", "Storeroom", "NB01", "No2"),
    ("Storeroom NB01 No3", "Storeroom", "NB01", "No3"),
    ("Storeroom NB02 No1", "Storeroom", "NB02", "No1"),
    ("Storeroom NB02 No2", "Storeroom", "NB02", "No2"),
    ("Storeroom NB02 No3", "Storeroom", "NB02", "No3"),
    ("Storeroom NB02 No4", "Storeroom", "NB02", "No4"),
    ("Storeroom NB03 No1", "Storeroom", "NB03", "No1"),
    ("Storeroom NB03 No2", "Storeroom", "NB03", "No2"),
    ("Storeroom NB03 No4", "Storeroom", "NB03", "No4"),
    ("Storeroom NB04 No1", "Storeroom", "NB04", "No1"),
    ("Storeroom NB04 No2", "Storeroom", "NB04", "No2"),
    ("Storeroom NB04 No3", "Storeroom", "NB04", "No3"),
    ("Storeroom NB05 No1", "Storeroom", "NB05", "No1"),
    ("Storeroom NB05 No2", "Storeroom", "NB05", "No2"),
    ("Storeroom NB05 No3", "Storeroom", "NB05", "No3"),
    ("Storeroom NB06 No1", "Storeroom", "NB06", "No1"),
    ("Storeroom NB06 No2", "Storeroom", "NB06", "No2"),
    ("Storeroom NB06 No3", "Storeroom", "NB06", "No3"),
    ("Storeroom NB06 No4", "Storeroom", "NB06", "No4"),
    ("Storeroom NB07 No1", "Storeroom", "NB07", "No1"),
    ("Storeroom NB07 No2", "Storeroom", "NB07", "No2"),
    ("Storeroom NB07 No3", "Storeroom", "NB07", "No3"),
    ("Storeroom NB08 No1", "Storeroom", "NB08", "No1"),
    ("Storeroom NB08 No2", "Storeroom", "NB08", "No2"),
    ("Storeroom NB09 No1", "Storeroom", "NB09", "No1"),
    ("Storeroom NB09 No2", "Storeroom", "NB09", "No2"),
    ("Storeroom NB09 No3", "Storeroom", "NB09", "No3"),
    ("Storeroom NB1", NULL, NULL, NULL),
    ("Storeroom NB10 No1", "Storeroom", "NB10", "No1"),
    ("Storeroom NB10 No2", "Storeroom", "NB10", "No2"),
    ("Storeroom NB11 No1", "Storeroom", "NB11", "No1"),
    ("Storeroom NB11 No2", "Storeroom", "NB11", "No2"),
    ("Storeroom NB12 No1", "Storeroom", "NB12", "No1"),
    ("Storeroom NB4 Box 5", NULL, NULL, NULL),
    ("Storeroom NB5 Box 1", NULL, NULL, NULL),
    ("Storeroom NB6 (3)", NULL, NULL, NULL),
    ("Storeroom NB8 No3", NULL, NULL, NULL),
    ("Storeroom NC01 No1", "Storeroom", "NC01", "No1"),
    ("Storeroom NC01 No2", "Storeroom", "NC01", "No2"),
    ("Storeroom NC02 No1", "Storeroom", "NC02", "No1"),
    ("Storeroom NC02 No2", "Storeroom", "NC02", "No2"),
    ("Storeroom NC02 No3", "Storeroom", "NC02", "No3"),
    ("Storeroom NC03 No1", "Storeroom", "NC03", "No1"),
    ("Storeroom NC03 No2", "Storeroom", "NC03", "No2"),
    ("Storeroom NC05 No1", "Storeroom", "NC05", "No1"),
    ("Storeroom NC05 No2", "Storeroom", "NC05", "No2"),
    ("Storeroom NC05 No3", "Storeroom", "NC05", "No3"),
    ("Storeroom NC06 No1", "Storeroom", "NC06", "No1"),
    ("Storeroom NC06 No2", "Storeroom", "NC06", "No2"),
    ("Storeroom NC08 No1", "Storeroom", "NC08", "No1"),
    ("Storeroom NC08 No2", "Storeroom", "NC08", "No2"),
    ("Storeroom NC09 No1", "Storeroom", "NC09", "No1"),
    ("Storeroom NC09 No2", "Storeroom", "NC09", "No2"),
    ("Storeroom NC09 No3", "Storeroom", "NC09", "No3"),
    ("Storeroom NC10 No1", "Storeroom", "NC10", "No1"),
    ("Storeroom NC10 No2", "Storeroom", "NC10", "No2"),
    ("Storeroom NC11 No1", "Storeroom", "NC11", "No1"),
    ("Storeroom NC11 No2", "Storeroom", "NC11", "No2"),
    ("Storeroom NC12", "Storeroom", "NC12", NULL),
    ("Storeroom ND01", "Storeroom", "ND01", NULL),
    ("Storeroom ND02", "Storeroom", "ND02", NULL),
    ("Storeroom ND03", "Storeroom", "ND03", NULL),
    ("Storeroom ND04", "Storeroom", "ND04", NULL),
    ("Storeroom ND05", "Storeroom", "ND05", NULL),
    ("Storeroom ND06", "Storeroom", "ND06", NULL),
    ("Storeroom ND07", "Storeroom", "ND07", NULL),
    ("Storeroom ND08 No1", "Storeroom", "ND08", "No1"),
    ("Storeroom ND08 No2", "Storeroom", "ND08", "No2"),
    ("Storeroom ND09 No1", "Storeroom", "ND09", "No1"),
    ("Storeroom ND12", "Storeroom", "ND12", NULL),
    ("Storeroom ND4", NULL, NULL, NULL),
    ("Storeroom SA03 No1", "Storeroom", "SA03", "No1"),
    ("Storeroom SA03 No2", "Storeroom", "SA03", "No2"),
    ("Storeroom SA03 No3", "Storeroom", "SA03", "No3"),
    ("Storeroom SA04 No1", "Storeroom", "SA04", "No1"),
    ("Storeroom SA04 No2", "Storeroom", "SA04", "No2"),
    ("Storeroom SA04 No3", "Storeroom", "SA04", "No3"),
    ("Storeroom SA05 No1", "Storeroom", "SA05", "No1"),
    ("Storeroom SA05 No2", "Storeroom", "SA05", "No2"),
    ("Storeroom SA05 No3", "Storeroom", "SA05", "No3"),
    ("Storeroom SA06 No1", "Storeroom", "SA06", "No1"),
    ("Storeroom SA06 No2", "Storeroom", "SA06", "No2"),
    ("Storeroom SA07", "Storeroom", "SA07", NULL),
    ("Storeroom SA3 (4)", NULL, NULL, NULL),
    ("Storeroom SB07 No1", "Storeroom", "SB07", "No1"),
    ("Storeroom SB07 No2", "Storeroom", "SB07", "No2"),
    ("Storeroom SB07 No3", "Storeroom", "SB07", "No3"),
    ("Storeroom SB07 No4", "Storeroom", "SB07", "No4"),
    ("Storeroom SB07 No5", "Storeroom", "SB07", "No5"),
    ("Storeroom SC01 No1", "Storeroom", "SC01", "No1"),
    ("Storeroom SC01 No2", "Storeroom", "SC01", "No2"),
    ("Storeroom SC01 No3", "Storeroom", "SC01", "No3"),
    ("Storeroom SD", "Storeroom", "SD", NULL),
    ("Storeroom SC02 No4", "Storeroom", "SC02", "No4"),
    ("Storeroom Sth Cupboard Bottom Shelf", "Storeroom", "Sth Cupboard Bottom Shelf", NULL),
    ("Storeroom Sth Cupboard Top Shelf", "Storeroom", "Sth Cupboard Top Shelf", NULL),
    ("Storeroom Top Shelf Above NA", "Storeroom", "Top Shelf Above NA", NULL),
    ("Storeroom WA01 No1", "Storeroom", "WA01", "No1"),
    ("Storeroom WA01 No2", "Storeroom", "WA01", "No2"),
    ("Storeroom WA02 No1", "Storeroom", "WA02", "No1"),
    ("Storeroom WA02 No2", "Storeroom", "WA02", "No2"),
    ("Storeroom WA02 No3", "Storeroom", "WA02", "No3"),
    ("Storeroom WA03 No1", "Storeroom", "WA03", "No1"),
    ("Storeroom WA03 No2", "Storeroom", "WA03", "No2"),
    ("Storeroom WA03 No3", "Storeroom", "WA03", "No3"),
    ("Storeroom WD02", "Storeroom", "WD02", NULL),
    ("Storeroom, Box 2", NULL, NULL, NULL),
    ("Storeroom, NA7 No 1", NULL, NULL, NULL),
    ("Supreme Court Gardens, Perth", NULL, NULL, NULL),
    ("Textile Box 4", NULL, NULL, "Textile Box 4"),
    ("Top Room", "Top Room", NULL, NULL),
    ("Top Room, Cabinet South Wall", NULL, NULL, NULL),
    ("Top Room, Top Cabinet", NULL, NULL, NULL),
    ("Top Room, Westwall (near door)", "Top Room", "Westwall (near door)", NULL),
    ("Town Hall, Barrack st., Perth", NULL, NULL, NULL),
    ("Tranby Room", "Tranby Room", NULL, NULL),
    ("Tranby Room 13", NULL, NULL, NULL),
    ("Tranby Room 29B", "Tranby Room", "29B", NULL),
    ("Tranby Room 30B", "Tranby Room", "30B", NULL),
    ("Tranby Room Box 15", NULL, NULL, NULL),
    ("Tranby Room Cardboard box", "Tranby Room", NULL, "Cardboard box"),
    ("Tranby Room Doll Box 06", "Tranby Room", NULL, "Doll Box 06"),
    ("Tranby Room Drawer", "Tranby Room", "Drawer", NULL),
    ("Tranby Room Drawer 01", "Tranby Room", "Drawer 01", NULL),
    ("Tranby Room Drawer 02", "Tranby Room", "Drawer 02", NULL),
    ("Tranby Room Drawer 03", "Tranby Room", "Drawer 03", NULL),
    ("Tranby Room Drawer 04", "Tranby Room", "Drawer 04", NULL),
    ("Tranby Room Drawer 05", "Tranby Room", "Drawer 05", NULL),
    ("Tranby Room Drawer 06", "Tranby Room", "Drawer 06", NULL),
    ("Tranby Room Drawer 07", "Tranby Room", "Drawer 07", NULL),
    ("Tranby Room Drawer 08", "Tranby Room", "Drawer 08", NULL),
    ("Tranby Room Drawer 09", "Tranby Room", "Drawer 09", NULL),
    ("Tranby Room Drawer 1", "Tranby Room", "Drawer 1", NULL),
    ("Tranby Room Drawer 10", "Tranby Room", "Drawer 10", NULL),
    ("Storeroom SC02 No6", NULL, NULL, NULL),
    ("Storeroom SA06 No3", "Storeroom", "SA06", "No3"),
    ("Tranby Room Box Silk Programs", "Tranby Room", NULL, "Box Silk Programs"),
    ("Art Store Shelf K", "Art Store", "Shelf K", NULL),
    ("Costume Room Top Shelf TSbb", "Costume Room", "Top Shelf", "TSbb"),
    ("Tranby Room Drawer 11", "Tranby Room", "Drawer 11", NULL),
    ("Tranby Room Drawer 12", "Tranby Room", "Drawer 12", NULL),
    ("Tranby Room Drawer 13", "Tranby Room", "Drawer 13", NULL),
    ("Tranby Room Drawer 14", "Tranby Room", "Drawer 14", NULL),
    ("Tranby Room Drawer 15", "Tranby Room", "Drawer 15", NULL),
    ("Tranby Room Drawer 16", "Tranby Room", "Drawer 16", NULL),
    ("Tranby Room Drawer 17", "Tranby Room", "Drawer 17", NULL),
    ("Tranby Room Drawer 18", "Tranby Room", "Drawer 18", NULL),
    ("Tranby Room Drawer 19", "Tranby Room", "Drawer 19", NULL),
    ("Tranby Room Drawer 2", NULL, NULL, NULL),
    ("Tranby Room Drawer 20", "Tranby Room", "Drawer 20", NULL),
    ("Tranby Room Drawer 21", "Tranby Room", "Drawer 21", NULL),
    ("Tranby Room Drawer 22", "Tranby Room", "Drawer 22", NULL),
    ("Tranby Room Drawer 23", "Tranby Room", "Drawer 23", NULL),
    ("Tranby Room Drawer 26", "Tranby Room", "Drawer 26", NULL),
    ("Tranby Room Drawer 27J", NULL, NULL, NULL),
    ("Tranby Room Drawer 27P", NULL, NULL, NULL),
    ("Tranby Room Drawer 27Q", "Tranby Room", "Drawer 27Q", NULL),
    ("Tranby Room Drawer 28E", NULL, NULL, NULL),
    ("Tranby Room Drawer 28H", "Tranby Room", NULL, NULL),
    ("Tranby Room Drawer 28L", NULL, NULL, NULL),
    ("Tranby Room Drawer 28M", NULL, NULL, NULL),
    ("Tranby Room Drawer 28N", NULL, NULL, NULL),
    ("Tranby Room Drawer 29C", NULL, NULL, NULL),
    ("Tranby Room Drawer 29E", NULL, NULL, NULL),
    ("Tranby Room Drawer 29f", NULL, NULL, NULL),
    ("Tranby Room Drawer 29G", NULL, NULL, NULL),
    ("Tranby Room Drawer 29J", NULL, NULL, NULL),
    ("Tranby Room Drawer 29K", NULL, NULL, NULL),
    ("Tranby Room Drawer 29N", NULL, NULL, NULL),
    ("Tranby Room Drawer 29Q", "Tranby Room", "Drawer 29Q", NULL),
    ("Tranby Room Drawer 29R", NULL, NULL, NULL),
    ("Tranby Room Drawer 30 D", NULL, NULL, NULL),
    ("Tranby Room Drawer 30 Q", NULL, NULL, NULL),
    ("Tranby Room Drawer 30 S", NULL, NULL, NULL),
    ("Tranby Room Drawer 30B", "Tranby Room", "Drawer 30B", NULL),
    ("Tranby Room Drawer 30C", "Tranby Room", "Drawer 30C", NULL),
    ("Tranby Room Drawer 30E", "Tranby Room", "Drawer 30E", NULL),
    ("Tranby Room Drawer 30I", NULL, NULL, NULL),
    ("Tranby Room Drawer 30R", "Tranby Room", "Drawer 30R", NULL),
    ("Tranby Room Drawer 30T", "Tranby Room", "Drawer 30T", NULL),
    ("Tranby Room Drawer 30U", NULL, NULL, NULL),
    ("Tranby Room Drawer 30V", NULL, NULL, NULL),
    ("Tranby Room Drawer 30W", "Tranby Room", NULL, NULL),
    ("Tranby Room Drawer 7", "Tranby Room", "Drawer 7", NULL),
    ("Tranby Room Drawer 9", "Tranby Room", "Drawer 9", NULL),
    ("Tranby Room Drawer30L", "Tranby Room", NULL, NULL),
    ("Tranby Room Reference Shelf", "Tranby Room", "Reference Shelf", NULL),
    ("Tranby Room Textiles Box 1", "Tranby Room", NULL, "Textiles Box 1"),
    ("Tranby Room Textiles Box 10", "Tranby Room", NULL, "Textiles Box 10"),
    ("Tranby Room Textiles Box 11", "Tranby Room", NULL, "Textiles Box 11"),
    ("Tranby Room Textiles Box 2", "Tranby Room", NULL, "Textiles Box 2"),
    ("Tranby Room Textiles Box 3", "Tranby Room", NULL, "Textiles Box 3"),
    ("Tranby Room Textiles Box 4", "Tranby Room", NULL, "Textiles Box 4"),
    ("Tranby Room Textiles Box 5", "Tranby Room", NULL, "Textiles Box 5"),
    ("Tranby Room Textiles Box 6", "Tranby Room", NULL, "Textiles Box 6"),
    ("Tranby Room Textiles Box 7", "Tranby Room", NULL, "Textiles Box 7"),
    ("Tranby Room Textiles Box 8", "Tranby Room", NULL, "Textiles Box 8"),
    ("Tranby Room Textiles Box 9", "Tranby Room", NULL, "Textiles Box 9"),
    ("Tranby Room, Box on Map Cases", NULL, NULL, NULL),
    ("Tranby Room, Manchester Cupboard", "Tranby Room", NULL, NULL),
    ("VAM Hobbs Foyer", NULL, NULL, NULL),
    ("XL", NULL, NULL, NULL),
    ("XL1", NULL, NULL, NULL),
    ("XXL", NULL, NULL, NULL),
    ("Photographs Room, B2", NULL, NULL, NULL),
    ("Tranby Room Box 01", "Tranby Room", NULL, "Box 01"),
    ("Tranby Room Box 02", "Tranby Room", NULL, "Box 02"),
    ("Tranby Room Box 03", "Tranby Room", NULL, "Box 03"),
    ("Tranby Room Box 04", "Tranby Room", NULL, "Box 04"),
    ("Photographs Room, Cabinet 3B,", "Photographs Room", "Cabinet 3B", NULL),
    ("Photographs Room, Phil Wyndham Collection", "Photographs Room", "Phil Wyndham Collection", NULL),
    ("De-accessioning Box", NULL, NULL, "De-accessioning Box"),
    ("Rare Book Cupboard", NULL, "Rare Book Cupboard", NULL),
    ("Textile Box 11", NULL, NULL, "Textile Box 11"),
    ("Textile Box 03", NULL, NULL, "Textile Box 03"),
    ("Map cabinet", "Library", "Annex, Map cabinet", NULL),
    ("Storeroom ND11", "Storeroom", "ND11", NULL),
    ("Textile Box 02", NULL, NULL, "Textile Box 02"),
    ("Storeroom NB03 No5", "Storeroom", "NB03", "5"),
    ("Tranby Room Doll Box 16", "Tranby Room", NULL, "Doll Box 16"),
    ("Exh - Homemade in WA", NULL, "Exh - Homemade in WA", NULL),
    ("Tranby Room Doll Box 10", "Tranby Room", NULL, "Doll Box 10"),
    ("Tranby Room Box 17", "Tranby Room", NULL, "Box 17"),
    ("Tranby Room Box 05", "Tranby Room", NULL, "Box 05"),
    ("Tranby Room Box 12", "Tranby Room", NULL, "Box 12"),
    ("Costume Room Top Shelf Box X", "Costume Room", "Top Shelf", "Box X"),
    ("Storeroom Shelf E1", "Storeroom", "E1", NULL),
    ("Costume Room Box 018", "Costume Room", NULL, "Box 018"),
    ("Storeroom NA08a No1", "Storeroom", "NA08a", "No1"),
    ("Storeroom SC02 No1", "Storeroom", "SC02", "No1"),
    ("Storeroom SC02 No2", "Storeroom", "SC02", "No2"),
    ("Storeroom SC02 No3", "Storeroom", "SC02", "No3"),
    ("Storeroom SC02 No5", "Storeroom", "SC02", "No5"),
    ("Passage", "Passage", NULL, NULL),
    ("Costume Room Top Shelf Box Z", "Costume Room", "Top Shelf", "Z"),
    ("Tranby Room Doll Box 18", "Tranby Room", NULL, "18"),
    ("Costume Room Top Shelf Box Y", "Costume Room", "Top Shelf", "Y"),
    ("Shipping Container", "Shipping Container", NULL, NULL),
    ("Tranby Room Box 6", "Tranby Room", NULL, "Box 6"),
    ("Costume Room Lower Hat Box Shelf", "Costume Room", "Lower Hat Box Shelf", NULL),
    ("Art Store A10", "Art Storeroom", "A10", NULL),
    ("Art Storeroom C10", "Art Storeroom", "C10", NULL),
    ("Art Store South Wall Top Shelf", "Art Store", "South Wall, Top Shelf", NULL),
    ("Tranby Room Doll Box 01", "Tranby Room", NULL, "Doll Box 01"),
    ("Tranby Room Doll Box 02", "Tranby Room", NULL, "Doll Box 02"),
    ("Tranby Room Doll Box 03", "Tranby Room", NULL, "Doll Box 03"),
    ("Tranby Room Doll Box 04", "Tranby Room", NULL, "Doll Box 04"),
    ("Tranby Room Doll Box 05", "Tranby Room", NULL, "Doll Box 05"),
    ("Tranby Room Doll Box 07", "Tranby Room", NULL, "Doll Box 07"),
    ("Tranby Room Doll Box 08", "Tranby Room", NULL, "Doll Box 08"),
    ("Tranby Room Doll Box 09", "Tranby Room", NULL, "Doll Box 09"),
    ("Tranby Room Doll Box 11", "Tranby Room", NULL, "Doll Box 11"),
    ("Tranby Room Doll Box 12", "Tranby Room", NULL, "Doll Box 12"),
    ("Tranby Room Doll Box 13", "Tranby Room", NULL, "Doll Box 13"),
    ("Tranby Room Doll Box 14", "Tranby Room", NULL, "Doll Box 14"),
    ("Tranby Room Doll Box 15", "Tranby Room", NULL, "Doll Box 15"),
    ("Tranby Room Doll Box 17", "Tranby Room", NULL, "Doll Box 17"),
    ("Tranby Room Doll Box 19", "Tranby Room", NULL, "Doll Box 19"),
    ("Storeroom SA06 No4", "Storeroom", "SA06", "No4"),
    ("Photographs Room, L4", "Photographs Room", "L4", NULL),
    ("Costume Room Box 030", "Costume Room", NULL, "30"),
    ("Costume Room Box 077", "Costume Room", NULL, "77"),
    ("Costume Room Box 096", "Costume Room", NULL, "96"),
    ("Costume Room Box 120", "Costume Room", NULL, "120"),
    ("Tranby Room Doll Box 20", "Tranby Room", "Doll Box 20", "Doll Box 20");

