#!/usr/bin/env bash

# halt on any errors or undefined variables
set -e
set -u

# load environment settings
pushd `dirname "$0"`>/dev/null
source ../env
source ../bin/importData
function refreshData() {
    sqltransform SubjectsExportView.sql
}

# setup local variables
mapping=rwahsSubjectListMapping
mapping_id="1zKHsF977x6SlQN7JtvnN-F4mGlNNcMClcwBAT_967zU"
# https://docs.google.com/spreadsheets/d/1zKHsF977x6SlQN7JtvnN-F4mGlNNcMClcwBAT_967zU/edit#gid=0

mapping_machine_name=subjectList
sourceTable=SubjectsExport

importData "$@"
popd > /dev/null
